wandb_version: 1

Vmax (C51 param):
  desc: null
  value: 10
Vmin (C51 param):
  desc: null
  value: -10
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.7.10
      5: 0.11.0
      8:
      - 5
alpha:
  desc: null
  value: 0.2
batch_size:
  desc: null
  value: 32
beta:
  desc: null
  value: 0.6
buffer_size:
  desc: null
  value: 2000
env_name:
  desc: null
  value: Molding_ENV
epsilon_for_priority:
  desc: null
  value: 1.0e-06
gamma:
  desc: null
  value: 0.99
initial_std (NoisyNet param):
  desc: null
  value: 0.5
input_dim:
  desc: null
  value: 400
learning_rate:
  desc: null
  value: 0.0001
n_atoms (C51 param):
  desc: null
  value: 51
n_step (Multi-step param):
  desc: null
  value: 4
skipped_frame:
  desc: null
  value: 0
soft_update_tau:
  desc: null
  value: 0.002
target_update_freq (unit:frames):
  desc: null
  value: 200
total_training_frames:
  desc: null
  value: 20000
update_start_buffer_size:
  desc: null
  value: 200
update_type:
  desc: null
  value: hard
