wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      4: 3.7.10
      5: 0.11.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 2000
env_name:
  desc: null
  value: Mold_ENV
eps_decay:
  desc: null
  value: 0.0005
eps_max:
  desc: null
  value: 1.0
eps_min:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
input_dim:
  desc: null
  value: 400
learning_rate:
  desc: null
  value: 0.001
soft_update_tau:
  desc: null
  value: 0.002
target_update_freq (unit:frames):
  desc: null
  value: 100
update_start_buffer_size:
  desc: null
  value: 200
update_type:
  desc: null
  value: hard
